package mydb;
// Generated 12-feb-2020 18:14:40 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Comentario generated by hbm2java
 */
@Entity
@Table(name="Comentario"
    ,catalog="mydb"
)
public class Comentario  implements java.io.Serializable {


     private Integer idComentario;
     private Cuadro cuadro;
     private Usuario usuario;
     private Date fecha;

    public Comentario() {
    }

	
    public Comentario(Cuadro cuadro, Usuario usuario) {
        this.cuadro = cuadro;
        this.usuario = usuario;
    }
    public Comentario(Cuadro cuadro, Usuario usuario, Date fecha) {
       this.cuadro = cuadro;
       this.usuario = usuario;
       this.fecha = fecha;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_comentario", unique=true, nullable=false)
    public Integer getIdComentario() {
        return this.idComentario;
    }
    
    public void setIdComentario(Integer idComentario) {
        this.idComentario = idComentario;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_cuadro", nullable=false)
    public Cuadro getCuadro() {
        return this.cuadro;
    }
    
    public void setCuadro(Cuadro cuadro) {
        this.cuadro = cuadro;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_usuario", nullable=false)
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha", length=19)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }




}


