package src;
// Generated 10-feb-2020 9:29:43 by Hibernate Tools 4.3.1



/**
 * Usuarios generated by hbm2java
 */
public class Usuarios  implements java.io.Serializable {


     private int idUsuarios;
     private String nombre;

    public Usuarios() {
    }

	
    public Usuarios(int idUsuarios) {
        this.idUsuarios = idUsuarios;
    }
    public Usuarios(int idUsuarios, String nombre) {
       this.idUsuarios = idUsuarios;
       this.nombre = nombre;
    }
   
    public int getIdUsuarios() {
        return this.idUsuarios;
    }
    
    public void setIdUsuarios(int idUsuarios) {
        this.idUsuarios = idUsuarios;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }




}


